### PR TITLE
[Tests] add passing tests

### LINKED ISSUE #167: Incorrect interpolation when using number prefix for Arabic content
There seems to be an issue regarding interpolation with Arabic string when template value start with a number.
```
var Polyglot = require("node-polyglot")
var polyglot = new Polyglot({interpolation: { prefix: '${', suffix: '}' }});

polyglot.extend({
  "hello_name": "الرمز ${code} غير صحيح"});

// works fine: CASE-A
polyglot.t("hello_name", {code: "De30Niro"});

// number goes at the beginning: CASE-B
polyglot.t("hello_name", {code: "30DeNiro"});
```

**Results**:
**CASE-A**:
image

**CASE-B:**
image

### PR DESCRIPTION
**Pull request by ljharb**
Closes #167

### CODE REVIEW

**Comment by ljharb** [comment]
goody, all the tests are passing. i'll put up a PR shortly converting to GHA.

File: test/index.js [hunk 1]
```diff
@@ -214,6 +214,22 @@ describe('locale-specific pluralization rules', function () {
...
+    };
+
+    var polyglot = new Polyglot({
+      phrases: phrases,
+      locale: 'ar',
+      interpolation: { prefix: '${', suffix: '}' }
+    });
+
+    expect(polyglot.t('hello', { code: 'De30Niro' })).to.equal('الرمز De30Niro غير صحيح');
+    expect(polyglot.t('hello', { code: '30DeNiro' })).to.equal('الرمز 30DeNiro غير صحيح');
```
Comment (lencioni) [inline test/index.js:229]: I don't know enough about this to be certain that this assertion is correct. Is there something I could reference?

Comment (ljharb) [reply test/index.js:229]: The linked issue has a bunch of relevant discussion.

Comment (lencioni) [reply test/index.js:229]: Ah, I see, thank you! Can you please add a code comment that explains that this can't be easily handled in polyglot and include a link to the discussion?

Comment (ljharb) [reply test/index.js:231]: sure, updated

**Comment by lencioni** [comment]
@ljharb looks like the automatic rebase is failing now. Is that something I need to tweak in the settings?

**Comment by ljharb** [comment]
no; i'm not sure why that one failed - `fatal: unsafe repository ('/github/workspace' is owned by someone else)` in the logs suggest it's something not specific to this repo. I'll look into it - if it's breaking, it'll be failing in all my other repos too, so it'll be a top priority for me :-)
